export * from './error/error.component';
export * from './error/error.route';
export * from './main/main.component';
export * from './footer/footer.component';
export * from './navbar/navbar.component';
export * from './navbar/navbar.route';
export * from './profiles/page-ribbon.component';
export * from './profiles/profile.service';
export * from './profiles/profile-info.model';
export * from './phase1/phase1.component';
export * from './phase2/phase2.component';
export * from './phase3/phase3.component';
export * from './phase4/phase4.component';
export * from './phase5/phase5.component';
export * from './navig/navig.component';
/*export * from './navig/navig.route';*/
